---
- name: Deploy application
  hosts: webservers
  become: yes
  vars_files:
    - ../group_vars/all.yml

  # tasks:
  #   - name: Force include vault vars
  #     include_vars:
  #       file: group_vars/all.yml
  #     no_log: true

  roles:
    - app_deploy
