plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  tag:Name: lab4-vm
keyed_groups:
  - key: tags.Name
    prefix: tag
groups:
  webservers: "true"
compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'/Users/dianayakupova/Study/DevOps/lab01/DevOps-Core-Course/ansible/keys/labsuser.pem'"
