$ANSIBLE_VAULT;1.1;AES256
61633465323462616430346461646631326336373838666563366235363639306436633630623139
3463323436343238363737333264386531643361336265640a323563636539333739376334386362
35633134336566316262623766336435373138633864363935323063623837386162353063333566
3863653966313631330a666562613263653235363331303635623635373137316138363839386339
30623437393161333731663466333132653364653162313765313930333431646534323331636335
34366439616263356539316335313561613465383434643331323033353938316661323133363436
63303161313732616335373133336665343531613039383537343630306162396664336232666639
63643938396363636138626334323232656430376362393863636237396536363565626638633037
37373336616132623431313336353133396332613535616466643138393435333833346139653930
3763333962613735623866303234356638366439623463323830
