---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure common packages are installed
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    install_recommends: no

- name: Ensure timezone is set to UTC
  community.general.timezone:
    name: "UTC"
  when: ansible_facts['os_family'] == "Debian"
