---
app_name: devops-app
app_port: 5000
app_container_name: "{{ app_name }}"
docker_image: "{{ dockerhub_username | default('REPLACE_ME') }}/{{ app_name }}"
docker_image_tag: latest
restart_policy: unless-stopped
